##############################
 
#!/bin/bash
 
#PBS -N CATempField
 
#PBS -l walltime=72:00:00
 
#PBS -l select=3:ncpus=48:mpiprocs=30:mem=180gb

#PBS -P ne_ldrd  

#PBS -M tteng2@ncsu.edu
 
cd $PBS_O_WORKDIR
 
module purge
module load use.moose moose-dev-openmpi/2025.09.18

##module load pbs
## module load cmake/3.27.7-gcc-12.3.0-5cfk
## module load gcc/12.3.0-gcc-10.5.0-vx2f
## module load mvapich2/2.3.7-1-gcc-12.3.0
## ml use.moose moose-dev-openmpi/2025.03.24
##module load cmake/3.22.3-gcc-9.3.0-ngra gcc/9.3.0-gcc-4.8.5-twls openmpi/4.0.5_ucx1.9
##module load mvapich2 cmake
##module load use.moose PETSc/3.11.4-GCC
 
##module load PETSc/3.10.3-foss-2018b
##module load MVAPICH2/2.2-GCC-5.4.0-2.28
##module load PETSc
##export OMP_NUM_THREADS=1


##which mpiexec
mpiexec -n 90 moose-dev-exec /home/tengtsu/projects_moose/malamute/malamute-opt -i New_Mat_DED_velocity_gaussian_heat_source_6_Sampler_EllipsoidSource_Undercool_CATemp_Src_FlatSurface.i -log_view >> 20251002_MALAMUTE_TempField_FlatSurface_v1058_3.log
##mpiexec -n 90 /home/tengtsu/projects_moose/malamute/malamute-opt -i New_Mat_DED_velocity_gaussian_heat_source_6_Sampler_EllipsoidSource_Undercool_CATemp_Src_FlatSurface.i -log_view >> 20251001_MALAMUTE_TempField_FlatSurface_v847.log

## mpiexec -n 48 moose-dev-exec /scratch/tengt/MOOSE_Submit_Job/W_grain_growth/grain_growth_2D_graintracker_mod3_5_TimeScaleAdapt/phase_field-opt -i grain_growth_2D_graintracker_mod3_5_TimeScaleAdapt.i
## mpiexec -n 48 moose-dev-exec $HOME/projects/marmot/marmot-opt -i 2024_09_11_darkzone_subgrain_nuc4_T1000_scaling3_baseline.i -log_view >> 2024_09_11_darkzone_subgrain_nuc4_T1000_scaling3_baseline.log
## mpiexec $HOME/projects/marmot/marmot-opt -i HBS_bub_vol_test.i -log_view >> HBS_bub_vol_test.log

#############################
date     #! print date and time